//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Ethan's Stuff/Controller Support Stuff/TheControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TheControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TheControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TheControls"",
    ""maps"": [
        {
            ""name"": ""game"",
            ""id"": ""2dcac892-2a5a-4320-a92b-91d117009dc4"",
            ""actions"": [
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""da55f408-086d-432c-ae54-d097b0a6bec4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""04fbe600-1996-48e3-a668-1707d750f527"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""dd7b3ff5-fd7b-4abb-84ab-26b1ad5a9279"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventory L"",
                    ""type"": ""Button"",
                    ""id"": ""1eb3090a-2122-4be3-9cad-7af05818665c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventory R"",
                    ""type"": ""Button"",
                    ""id"": ""e33ee82c-aeb4-44b3-ba73-f5db6142f97a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Open Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""81f61e44-8820-4981-8734-289cdb02f940"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""08790f6c-2697-49ff-bd47-540e6c8403d7"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d713f28-5ca5-42f4-b780-432c8332b2d3"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae35ff1c-d889-49f7-8c59-1fef5e72e313"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fca0e534-2f43-40fe-9ef1-bfae63e9d6d6"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""676add89-d6fa-497e-97dd-307f333da5d4"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory L"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06531f8c-8efc-4955-9895-6ae20b48ecac"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Inventory L"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4420e1a-d80e-4668-b72f-3232cbcdb66a"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory R"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69d8ee4f-0a0a-4087-8979-2fd0a9185e5b"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Inventory R"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5de96d7-64fd-4754-88bb-32aaaf5c637b"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c8ef0af5-c75f-419c-a44c-4f2ef409551e"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1354c8cd-e95e-41e1-ae95-d34679fcac3c"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Open Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bfbe8f57-f83c-44d8-a529-36a5f9dc5bad"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Open Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""dialogue"",
            ""id"": ""bab76d42-d75a-41f8-8322-51e545c685e7"",
            ""actions"": [
                {
                    ""name"": ""Progress Dialogue"",
                    ""type"": ""Button"",
                    ""id"": ""c56c5a04-1ae8-4adb-9ec7-126cadb653c8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""69a9c783-89b1-4cb6-9657-363a74984196"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Progress Dialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1cd15954-b773-4188-840a-15d3fb1a70e5"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Progress Dialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c860960d-760b-4edc-8158-dcbada2b81c1"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Progress Dialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""inventory"",
            ""id"": ""a994701e-56d8-4f5a-b811-ae88568d0d89"",
            ""actions"": [
                {
                    ""name"": ""close inventory"",
                    ""type"": ""Button"",
                    ""id"": ""1a57d52b-5b07-45a9-b8f4-86a8606e578d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b423bd63-41a7-4a51-ae25-6559934920f3"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""close inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31d6a131-2eca-438a-9a07-657f58350ba7"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""close inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Controller"",
            ""bindingGroup"": ""Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // game
        m_game = asset.FindActionMap("game", throwIfNotFound: true);
        m_game_Sprint = m_game.FindAction("Sprint", throwIfNotFound: true);
        m_game_Interact = m_game.FindAction("Interact", throwIfNotFound: true);
        m_game_Pause = m_game.FindAction("Pause", throwIfNotFound: true);
        m_game_InventoryL = m_game.FindAction("Inventory L", throwIfNotFound: true);
        m_game_InventoryR = m_game.FindAction("Inventory R", throwIfNotFound: true);
        m_game_OpenInventory = m_game.FindAction("Open Inventory", throwIfNotFound: true);
        // dialogue
        m_dialogue = asset.FindActionMap("dialogue", throwIfNotFound: true);
        m_dialogue_ProgressDialogue = m_dialogue.FindAction("Progress Dialogue", throwIfNotFound: true);
        // inventory
        m_inventory = asset.FindActionMap("inventory", throwIfNotFound: true);
        m_inventory_closeinventory = m_inventory.FindAction("close inventory", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // game
    private readonly InputActionMap m_game;
    private IGameActions m_GameActionsCallbackInterface;
    private readonly InputAction m_game_Sprint;
    private readonly InputAction m_game_Interact;
    private readonly InputAction m_game_Pause;
    private readonly InputAction m_game_InventoryL;
    private readonly InputAction m_game_InventoryR;
    private readonly InputAction m_game_OpenInventory;
    public struct GameActions
    {
        private @TheControls m_Wrapper;
        public GameActions(@TheControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Sprint => m_Wrapper.m_game_Sprint;
        public InputAction @Interact => m_Wrapper.m_game_Interact;
        public InputAction @Pause => m_Wrapper.m_game_Pause;
        public InputAction @InventoryL => m_Wrapper.m_game_InventoryL;
        public InputAction @InventoryR => m_Wrapper.m_game_InventoryR;
        public InputAction @OpenInventory => m_Wrapper.m_game_OpenInventory;
        public InputActionMap Get() { return m_Wrapper.m_game; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameActions set) { return set.Get(); }
        public void SetCallbacks(IGameActions instance)
        {
            if (m_Wrapper.m_GameActionsCallbackInterface != null)
            {
                @Sprint.started -= m_Wrapper.m_GameActionsCallbackInterface.OnSprint;
                @Sprint.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnSprint;
                @Sprint.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnSprint;
                @Interact.started -= m_Wrapper.m_GameActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnInteract;
                @Pause.started -= m_Wrapper.m_GameActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnPause;
                @InventoryL.started -= m_Wrapper.m_GameActionsCallbackInterface.OnInventoryL;
                @InventoryL.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnInventoryL;
                @InventoryL.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnInventoryL;
                @InventoryR.started -= m_Wrapper.m_GameActionsCallbackInterface.OnInventoryR;
                @InventoryR.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnInventoryR;
                @InventoryR.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnInventoryR;
                @OpenInventory.started -= m_Wrapper.m_GameActionsCallbackInterface.OnOpenInventory;
                @OpenInventory.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnOpenInventory;
                @OpenInventory.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnOpenInventory;
            }
            m_Wrapper.m_GameActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @InventoryL.started += instance.OnInventoryL;
                @InventoryL.performed += instance.OnInventoryL;
                @InventoryL.canceled += instance.OnInventoryL;
                @InventoryR.started += instance.OnInventoryR;
                @InventoryR.performed += instance.OnInventoryR;
                @InventoryR.canceled += instance.OnInventoryR;
                @OpenInventory.started += instance.OnOpenInventory;
                @OpenInventory.performed += instance.OnOpenInventory;
                @OpenInventory.canceled += instance.OnOpenInventory;
            }
        }
    }
    public GameActions @game => new GameActions(this);

    // dialogue
    private readonly InputActionMap m_dialogue;
    private IDialogueActions m_DialogueActionsCallbackInterface;
    private readonly InputAction m_dialogue_ProgressDialogue;
    public struct DialogueActions
    {
        private @TheControls m_Wrapper;
        public DialogueActions(@TheControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @ProgressDialogue => m_Wrapper.m_dialogue_ProgressDialogue;
        public InputActionMap Get() { return m_Wrapper.m_dialogue; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DialogueActions set) { return set.Get(); }
        public void SetCallbacks(IDialogueActions instance)
        {
            if (m_Wrapper.m_DialogueActionsCallbackInterface != null)
            {
                @ProgressDialogue.started -= m_Wrapper.m_DialogueActionsCallbackInterface.OnProgressDialogue;
                @ProgressDialogue.performed -= m_Wrapper.m_DialogueActionsCallbackInterface.OnProgressDialogue;
                @ProgressDialogue.canceled -= m_Wrapper.m_DialogueActionsCallbackInterface.OnProgressDialogue;
            }
            m_Wrapper.m_DialogueActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ProgressDialogue.started += instance.OnProgressDialogue;
                @ProgressDialogue.performed += instance.OnProgressDialogue;
                @ProgressDialogue.canceled += instance.OnProgressDialogue;
            }
        }
    }
    public DialogueActions @dialogue => new DialogueActions(this);

    // inventory
    private readonly InputActionMap m_inventory;
    private IInventoryActions m_InventoryActionsCallbackInterface;
    private readonly InputAction m_inventory_closeinventory;
    public struct InventoryActions
    {
        private @TheControls m_Wrapper;
        public InventoryActions(@TheControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @closeinventory => m_Wrapper.m_inventory_closeinventory;
        public InputActionMap Get() { return m_Wrapper.m_inventory; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InventoryActions set) { return set.Get(); }
        public void SetCallbacks(IInventoryActions instance)
        {
            if (m_Wrapper.m_InventoryActionsCallbackInterface != null)
            {
                @closeinventory.started -= m_Wrapper.m_InventoryActionsCallbackInterface.OnCloseinventory;
                @closeinventory.performed -= m_Wrapper.m_InventoryActionsCallbackInterface.OnCloseinventory;
                @closeinventory.canceled -= m_Wrapper.m_InventoryActionsCallbackInterface.OnCloseinventory;
            }
            m_Wrapper.m_InventoryActionsCallbackInterface = instance;
            if (instance != null)
            {
                @closeinventory.started += instance.OnCloseinventory;
                @closeinventory.performed += instance.OnCloseinventory;
                @closeinventory.canceled += instance.OnCloseinventory;
            }
        }
    }
    public InventoryActions @inventory => new InventoryActions(this);
    private int m_ControllerSchemeIndex = -1;
    public InputControlScheme ControllerScheme
    {
        get
        {
            if (m_ControllerSchemeIndex == -1) m_ControllerSchemeIndex = asset.FindControlSchemeIndex("Controller");
            return asset.controlSchemes[m_ControllerSchemeIndex];
        }
    }
    public interface IGameActions
    {
        void OnSprint(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnInventoryL(InputAction.CallbackContext context);
        void OnInventoryR(InputAction.CallbackContext context);
        void OnOpenInventory(InputAction.CallbackContext context);
    }
    public interface IDialogueActions
    {
        void OnProgressDialogue(InputAction.CallbackContext context);
    }
    public interface IInventoryActions
    {
        void OnCloseinventory(InputAction.CallbackContext context);
    }
}
